<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccountGroupTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountGroupTypeRepository extends EntityRepository
{
}
