<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlertsConfiguration.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertsConfiguration extends EntityRepository
{
}
