<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RiaCompanyInformationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountTypeRepository extends EntityRepository
{
    public function getInvestmentTypes()
    {
        return $this->getAccountTypeByType('investment');
    }

    public function getRetirementTypes()
    {
        return $this->getAccountTypeByType('retirement');
    }

    public function getAccountTypeByType($accountType)
    {
        $q = $this->getEntityManager()->createQuery('SELECT t FROM App\Entity\ClientAccountType t
         WHERE t.type=:account_type');

        $q->setParameters(['account_type' => $accountType]);

        return $q->getResult();
    }

    public function getAllAsArray()
    {
        $accountTypes = $this->findAll();

        $result = [];
        foreach ($accountTypes as $accountType) {
            $result[$accountType->getId()] = $accountType->getType();
        }

        return $result;
    }
}
