<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Model\ClientAccount;

/**
 * BeneficiaryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeneficiaryRepository extends EntityRepository
{
    public function getBeneficiariesShareForAccount(ClientAccount $account, $type)
    {
        $dql = 'SELECT SUM(b.share) as percent
                FROM App\Entity\Beneficiary b
                WHERE b.account_id = :account_id AND b.type = :type GROUP BY b.account_id';

        $query = $this->getEntityManager()->createQuery($dql);
        $query->setMaxResults(1)
            ->setParameters([
                'account_id' => $account->getId(),
                'type' => $type,
            ]);

        $result = $query->getOneOrNullResult(2);

        return round($result['percent'], 2);
    }
}
