<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Entity\Bill;
use App\Entity\User;

/**
 * BillRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillRepository extends EntityRepository
{
    public function findByUserAndDate(User $user, \DateTime $dateFrom, \DateTime $dateTo)
    {
        return $this->createQueryBuilder('b')
            ->where('b.client = :user')
            ->andWhere('b.createdAt >= :dateFrom')
            ->andWhere('b.createdAt < :dateTo')
            ->orderBy('b.createdAt', 'DESC')
            ->setParameter('user', $user)
            ->setParameter('dateFrom', $dateFrom)
            ->setParameter('dateTo', $dateTo)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param User $client
     * @param $year
     * @param int $quarter
     *
     * @return Bill|null
     */
    public function findByClientAndPeriod(User $client, $year, $quarter = 0)
    {
        $qb = $this->createQueryBuilder('b')
            ->where('b.client = :user')
            ->andWhere('b.year = :year')
            ->setParameter('user', $client)
            ->setParameter('year', $year)
            ->setMaxResults(1)
        ;

        if (0 === $quarter) {
            $qb->orderBy('b.quarter', 'DESC');
        } else {
            $qb->andWhere('b.quarter = :quarter')->setParameter('quarter', $quarter);
        }

        return $qb->getQuery()->getOneOrNullResult();
    }
}
