<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientPortfolioRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientPortfolioRepository extends EntityRepository
{
}
