<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientAccountDocusignRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientAccountDocusignRepository extends EntityRepository
{
}
