<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DistributionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributionRepository extends EntityRepository
{
}
