<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JobRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayRepository extends EntityRepository
{
    public function getFromTo($dateFrom, $dateTo)
    {
        return $this->createQueryBuilder('h')
            ->where('h.date >= :dateFrom')
            ->andWhere('h.date < :dateTo')
            ->setParameter('dateFrom', $dateFrom)
            ->setParameter('dateTo', $dateTo)
            ->getQuery()
            ->getResult();
    }
}
