<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PortfolioTwrPeriodRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioTwrPeriodRepository extends EntityRepository
{
}
