<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
}
