<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RebalancerActionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RebalancerActionRepository extends EntityRepository
{
}
