<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RetirementPlanInformationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetirementPlanInformationRepository extends EntityRepository
{
}
