<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RiskAnswerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiskAnswerRepository extends EntityRepository
{
}
