<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TransactionTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionTypeRepository extends EntityRepository
{
    /**
     * @param null $name
     *
     * @return array
     */
    public function getAll($name = null)
    {
        $qb = $this->createQueryBuilder('t');

        if (!empty($name)) {
            $qb->where('t.name LIKE :name')->setParameter('name', "%{$name}%");
        }

        return $qb
            ->orderBy('t.name', 'ASC')
            ->getQuery()
            ->getResult()
        ;
    }
}
