<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientActivitySummaryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientActivitySummaryRepository extends EntityRepository
{
    public function findVisibleByRiaIdQuery($riaId, $limit = null)
    {
        $qb = $this->createQueryBuilder('cas')
            ->leftJoin('cas.client', 'c')
            ->leftJoin('c.profile', 'p')
            ->where('p.ria_user_id = :riaId')
            ->andWhere('cas.is_show_ria = true')
            ->setParameter('riaId', $riaId)
        ;

        if ($limit) {
            $qb->setMaxResults($limit);
        }

        return $qb->getQuery();
    }
}
