<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Model\ClientAccountOwner;
use App\Model\ClientAdditionalContact;

/**
 * ClientAccountOwnerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientAccountOwnerRepository extends EntityRepository
{
    public function findLastOtherOwnerByClientId($clientId)
    {
        $qb = $this->createQueryBuilder('ao');
        $qb->select('ao', 'ac')
            ->leftJoin('ao.contact', 'ac')
            ->where('ao.owner_type = :owner_type')
            ->andWhere('ac.type = :type')
            ->andWhere('ac.client_id = :client_id')
            ->orderBy('ao.id', 'desc')
            ->setMaxResults(1);

        $qb->setParameters([
            'owner_type' => ClientAccountOwner::OWNER_TYPE_OTHER,
            'type' => ClientAdditionalContact::TYPE_OTHER,
            'client_id' => $clientId,
        ]);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
