<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClosingMethodRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClosingMethodRepository extends EntityRepository
{
    /**
     * @param null $name
     *
     * @return array
     */
    public function getAll($name = null)
    {
        $qb = $this->createQueryBuilder('cm');

        if (!empty($name)) {
            $qb->where('cm.name LIKE :name')->setParameter('name', "%{$name}%");
        }

        return $qb
            ->orderBy('cm.name', 'ASC')
            ->getQuery()
            ->getResult()
        ;
    }
}
