<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustodianMessageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustodianMessageRepository extends EntityRepository
{
    public function findByCustodianId($custodianId)
    {
        return $this->findBy(['custodian_id' => $custodianId]);
    }

    public function findOneByCustodianIdAndType($custodianId, $type)
    {
        return $this->findOneBy(['custodian_id' => $custodianId, 'type' => $type]);
    }

    /**
     * Get associated array of custodian messages.
     * array(type => message).
     *
     * @param int $custodian_id
     *
     * @return array
     */
    public function getAssocByCustodianId($custodian_id)
    {
        $messages = $this->findByCustodianId($custodian_id);

        $result = [];
        foreach ($messages as $message) {
            $result[$message->getType()] = $message->getMessage();
        }

        return $result;
    }
}
