<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GainLossRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GainLossRepository extends EntityRepository
{
}
