<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Entity\Job;
use App\Entity\User;

/**
 * JobRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
    public function findLastRebalanceJobForUser(User $user)
    {
        $qb = $this->createQueryBuilder('j')
            ->where('j.user = :user')
            ->andWhere('j.name = :name')
            ->setParameters([
                'user' => $user,
                'name' => Job::JOB_NAME_REBALANCER,
            ])
            ->orderBy('j.finished_at', 'DESC')
            ->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function findIncompleteByRia(User $user)
    {
        $qb = $this->createQueryBuilder('j')
            ->where('j.user = :ria')
            ->andWhere('j.finished_at IS NULL')
            ->setParameter('ria', $user);

        return $qb->getQuery()->getResult();
    }
}
