<?php

namespace Wealthbot\ClientBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Wealthbot\ClientBundle\Entity\BillItem;
use Wealthbot\ClientBundle\Entity\ClientAccount;

/**
 * BillItemRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillItemRepository extends EntityRepository
{
    /**
     * @param ClientAccount $account
     * @param $year
     * @param int $quarter
     *
     * @return null|BillItem
     */
    public function getByAccountAndPeriod(ClientAccount $account, $year, $quarter = 0)
    {
        $systemAccount = $account->getSystemAccount();
        if (!$systemAccount) {
            return;
        }

        $qb = $this->createQueryBuilder('i')
            ->where('i.systemAccount = :systemAccount')
            ->leftJoin('i.bill', 'b')
            ->andWhere('b.year = :year')
            ->setParameter('systemAccount', $systemAccount)
            ->setParameter('year', $year)
            ->setMaxResults(1)
        ;

        if ($quarter === 0) {
            $qb->orderBy('b.quarter', 'DESC');
        } else {
            $qb->andWhere('b.quarter = :quarter')->setParameter('quarter', $quarter);
        }

        return $qb->getQuery()->getOneOrNullResult();
    }
}
