<?php

namespace Wealthbot\ClientBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TransferCustodianRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferCustodianRepository extends EntityRepository
{
}
